version: '3.7'
services:
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5435:5432
    networks:
      - notification

  kafka:
    image: bitnami/kafka
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - notification

networks:
  notification: 
    driver: bridge